version: 2.1
jobs:
  build:
    working_directory: /dockerappweb
    docker:
      - image: docker:22.06-rc-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Instalar dependencias
          command:

            apk add --no-cache py3-pip=22.1.1-r0

            pip install docker-compose==1.29.2

      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
