version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:22.06-rc-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command:
            apk add --no-cache py-pip=9.0.0-r1

            pip install --upgrade pip

            pip install docker-compose==2.11.2
      - run:
          name: Run tests
          command:
            docker-compose up -d
            docker-compose run appweb python test.py
